spring:
  application:
    name: custom-logger-interceptor
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG